sequenceDiagram

    actor User
    User ->> Main : run
    activate Main
    participant Apple
    Main ->> Apple : <<create>>
    Apple -->> Main : apple
    participant Tree
    Main ->> Tree : <<create>>
    Tree -->> Main : tree
    Main ->> Tree: addApple(apple)
    Tree ->> Tree: increaseAppleCount()
    Tree -->> Main : 
    participant Visualizer
    Main ->> Visualizer : <<create>>
    Visualizer -->> Main : visualizer
    Main ->> Visualizer : visualize(tree)
    Visualizer -->> Main : "tree: 1 apple"
    Main -->> User : 

   
    deactivate Main

